---

- name: deploy postgresql.conf file
  template:
    src: postgresql.conf.j2
    dest: "{{ pg_data_dir }}/postgresql.conf"
    owner: "{{ postgresql_user_name }}"
    group: "{{ postgresql_user_group }}"
    mode: 0600
  notify:
    - reload postgresql

- name: configure pg_hba_conf file
  template:
    src: pg_hba.conf.j2
    dest: "{{ pg_data_dir }}/pg_hba.conf"
    owner: "{{ postgresql_user_name }}"
    group: "{{ postgresql_user_group }}"
    mode: 0600
  when: postgresql_pg_hba_entries is defined and postgresql_pg_hba_entries | length > 0
  notify:
    - reload postgresql
