---

- name: restart postgresql
  service:
    name: "postgresql-{{ postgresql_version }}"
    state: restarted

- name: reload postgresql
  service:
    name: "postgresql-{{ postgresql_version }}"
    state: reloaded
