---

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ microservice_packages }}"

- name: create systemd service unit for microservices
  template:
    src: "microservice@.service.j2"
    dest: /etc/systemd/system/microservice@.service
    owner: root
    group: root

- name: create microservice's OS group
  group:
    name: "{{ microservice_os_group }}"

- name: create microservice's OS user
  user:
    name: "{{ microservice_os_user }}"
    group: "{{ microservice_os_group }}"

- name: deploy microservices
  include: deploy.yml
  with_items: "{{ microservice_instances }}"
  loop_control:
    loop_var: _microservice_instance_name
