---

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ base_packages }}"

- name: enable and optionally start required services
  service:
    name: "{{ item.key }}"
    enabled: "{{ item.value.enabled }}"
    state: "{{ item.value.state | default(omit) }}"
  with_dict:
    - "{{ base_services }}"
